### ISSUE TITLE
DeviceAddress 

### ISSUE THREAD

**Issue by joaobrittoneto** [Brazilian-Institute-of-Robotics/drivers-usbl_evologics#25]
The [DeviceAddress](https://github.com/Brazilian-Institute-of-Robotics/drivers-usbl_evologics/blob/master/src/DriverTypes.hpp#L192) is a little bit confusing. 
The number address is not the same in Bremen and Salvador.
In Bremen the FF is 2, and dock is 1, in Salvador the other way around.

In [DeviceSettings](https://github.com/Brazilian-Institute-of-Robotics/drivers-usbl_evologics/blob/master/src/DriverTypes.hpp#L293) the address is defined as number. 
The name scheme is only used in for the [EncodeIM](https://github.com/Brazilian-Institute-of-Robotics/drivers-orogen-auv_messaging/blob/master/auv_messaging.orogen#L53) (it seems). The other part of the usbl drives handles the numbers direct.

I'm thinking of remove this DeviceAddress entirely.
@g-arjones, @doudou, any suggestion?

**Comment by g-arjones** [comment]
I think these addresses belong in a config file rather then hardcoded in some header. I would say go ahead and remove this struct but be careful to only have the constant in one single config file and make everyone read from there otherwise it will be a nightmare to manage. Still, a constant for BROADCAST is ok (this one really is a constant)

**Comment by doudou** [comment]
I second @g-arjones - these should not be part of the usbl-evologics. :+1: to remove
